lib/syskit/gui/model_views/task_context.rb
lib/syskit/gui/model_views/type.rb

Already some time ago ```OroGen::HTML``` was renamed to ```OroGen::HTML``` (https://github.com/orocos-toolchain/orogen/commit/68377afa9d93ca7304ce74f30f84af7b5ce5d2cc). Syskit still used the old naming in  ```lib/syskit/gui/model_views/task_context.rb```
and ```lib/syskit/gui/model_views/type.rb```

Orocos::HTML is now named OroGen::HTML (cf. tools/orogen)

---

lib/syskit/roby_app/configuration.rb

Added missing require statement to include Orocos::RemoteProcesses::Client.
See also #43

connect_to_orocos_process_server failed to create Orocos::RemoteProcesses::Client

---

lib/syskit/roby_app/configuration.rb
lib/syskit/roby_app/plugin.rb

``` Syskit.conf.use_deployments_from("aila_vision_deployments", :on => "vision_cpu")``` led to the following error:
```
= /home/sempromuser/RockDev/tools/syskit/lib/syskit/roby_app/plugin.rb:268:in `using_task_library': unknown options 'on' (ArgumentError)
= Backtrace
| 
|   /home/sempromuser/RockDev/tools/syskit/lib/syskit/roby_app/plugin.rb:268:in `using_task_library'
|   /home/sempromuser/RockDev/tools/syskit/lib/syskit/roby_app/configuration.rb:410:in `use_deployments_from'
|   ./models/profiles/aila.rb:29:in `<top (required)>'
|   /home/sempromuser/RockDev/tools/syskit/bin/syskit:19:in `<main>'
```
This this PR fixes the problem by adding ```:on => "localhost"``` to the optione evaluation in ```using_task_library``` and ```using_deployment```

Allow to specify remote targets for deployments

---

lib/syskit/dependency_injection.rb
lib/syskit/gui/model_views/composition.rb
lib/syskit/instance_requirements.rb
lib/syskit/models/component.rb
lib/syskit/models/composition.rb
lib/syskit/models/data_service.rb
lib/syskit/network_generation/engine.rb
lib/syskit/robot/master_device_instance.rb
test/network_generation/test_engine.rb
test/test_dependency_injection.rb
test/test_instance_requirements.rb

So far, optional dependencies would be considered "not present" if,
at instanciation time, the dependency was not directly injected.
This is limited as the system network postprocessing is therefore not
allowed to actually replace non-selected optional dependencies by
implementations and have it picked up.
This commit moves the handling to #compute_system_network. This allows
to explicitely select services with tasks explicitely marked as abstract
(used as "matchers") which can then be replaced at network merge time.
E.g.
cmp.use('optional' => Cmp.use('src' => a_device).if_already_present)
will keep the optional dependency if the composition is present, and
will remove it otherwise

netgen: move handling of optional dependencies to network resolution

---

lib/syskit/gui/browse.rb
lib/syskit/gui/ide.rb
lib/syskit/gui/model_browser.rb
lib/syskit/gui/model_views/profile.rb
lib/syskit/scripts/ide.rb

syskit ide will in term replace syskit browse, but not quite yet.
For now, this is mostly like syskit browse, but with bugfixes, and with
the ability to open files in an external editor (needs some configuration)
Closes #63

gui: start the syskit ide subcommand

---

lib/syskit/instance_requirements.rb
lib/syskit/models/data_service.rb
lib/syskit/robot/master_device_instance.rb
lib/syskit/robot/robot_definition.rb
test/robot/test_robot_definition.rb
test/suite_robot.rb

The difference with the implementation in #47 is that we remove
the temporary variables for requirements & DI and directly build
an InstanceRequirements object under the hood. This adds validation
of the DI keys at the point where #use is called instead of doing
it later (and keeps the implementation if-free)

support compositions as device drivers (closes #47)

---

lib/syskit/actions/profile.rb
lib/syskit/dependency_injection.rb
lib/syskit/instance_requirements.rb
test/models/test_composition.rb
test/test_dependency_injection.rb
test/test_dependency_injection_context.rb

Closes https://github.com/rock-core/tools-syskit/issues/23
Interestingly, the profile-level API really does what the issue was asking: one can now choose 'nothing'
~~~
define 'bla', Bla.use('child' => nothing)
~~~

Support explicit deselection in dependency injection

---

lib/syskit/data_service.rb
lib/syskit/models/data_service.rb
lib/syskit/robot/communication_bus.rb
lib/syskit/robot/master_device_instance.rb
test/test_data_service.rb

Reconfiguring a com bus is really something that should be avoided at
all costs. The current policy would cause a reconfiguration each time
a device on the bus would be activated for the first time, which would
disrupt the already running devices.
The default policy, after this commit, is to create all dynamic
services on the bus that are required for all declared devices. One can
get the earlier behaviour by adding lazy_dispatch: true to the com bus
declaration.

configure com busses to handle all their devices (even unattached ones) by default

---

lib/syskit/deployment.rb

At the moment syskit no longer runs on ruby2.0 (Ubuntu 14.04) because of  private method call. This was changed in ruby 2.1.

Deployment: fix calling private method prepend (ruby 2.0)

---

lib/syskit/shell_interface.rb
test/suite.rb

The syskit.reload_config() was reporting "unknown configured method". This fix the error message, anything else need to be done?

fix NoMethodError when reloading configuration in the shell

---

lib/syskit/actions/action_model.rb
lib/syskit/instance_requirements.rb
test/actions/test_action_model.rb

On the user-visible side, this fixes displaying Syskit actions in the
roby shell.
Depends on:

actions: pass more information when droby-marshalling/demarshalling an action

---

lib/syskit/gui/runtime_state.rb
lib/syskit/gui/widget_list.rb

We can't interact with the batch manager while Syskit is unreachable.
Make sure that one cannot create new jobs in any way, and clear the
current batch if there's one.

disable any action-related interactions when Syskit is unreachable (closes #131)

---

lib/syskit/runtime/update_task_states.rb

This ensures that the chronicle view reports that a component is being configured (it was only saying 'not executable' before)

runtime: report on a scheduler when a component is being configured

---

lib/syskit/gui/page.rb

They are properly translated to &lt; and &gt; in the geneated dot, but
then dot converts them back to < and > in the SVG. This breaks SVG
parsing of e.g. inkscape.

fix dot's SVG output to not include < > in HREF's

---

lib/syskit/cli/gen_main.rb

They were using the class name (`gen_main`) by default

cli: fix help messages from 'syskit gen'

---

lib/syskit/gui/ide.rb
lib/syskit/gui/model_browser.rb
lib/syskit/gui/testing.rb
lib/syskit/roby_app/plugin.rb

Depends on:
It allows to add addition files, types or task models within a Syskit IDE without having to restart the IDE.
The PR also does some fine-tuning of the IDE model browsing: removes "utility" types (arrays, numeric types, m-types) from the type display, and renames "start" into "start tests"

ide: implement the "Add" button

---

lib/syskit/graphviz.rb

Apart from fixing confusing output, it also fixes the hyperlink of
a port to its type, after the removal of intermediate types from
the type list.

ide: display the real type and not the intermediate type

---

lib/syskit/gui/runtime_state.rb

Depends on: 
This improves error reporting in the first cycle(s) - that is, errors generated within the controller.

ide: start roby with --wait-shell-connection

---

lib/syskit/gui/ide.rb
lib/syskit/gui/runtime_state.rb
test/gui/test_runtime_state.rb

This is what was causing the "accessing disposed task context" error.
Reloading the models calls Orocos.clear, which in turn de-initializes
Orocos. It wasn't getting initialized again afterwards, and broke
everything.
There are other side effects - namely, that the name services are
also deinitialized. This creates new name services to avoid this.
Fixes #169

ide: fix interaction between reloading models and runtime view

---

lib/syskit/deployment.rb
lib/syskit/exceptions.rb
lib/syskit/graphviz.rb
lib/syskit/models/component.rb
lib/syskit/models/composition_child.rb
lib/syskit/network_generation/dataflow_computation.rb
lib/syskit/network_generation/dataflow_dynamics.rb
lib/syskit/network_generation/merge_solver.rb
lib/syskit/network_generation/system_network_deployer.rb
lib/syskit/orogen_namespace.rb
lib/syskit/test/self.rb
test/models/test_component.rb
test/network_generation/test_dataflow_dynamics.rb
test/network_generation/test_system_network_deployer.rb
test/test_deployment.rb

oroGen has had support integrated to define master/slave tasks. The rationale behind the feature was to declare that some tasks (the masters) are triggering some other tasks (the slaves). This is used to implement for instance single-threaded deployments, where the slave tasks are executed explicitely by the master, in a predefined order. An implementation of this scheme is for instance the [`slave_scheduler`](https://github.com/ThirteenLtda/tools-orogen-slave_scheduler)
This integrates the functionality in Syskit. The master tasks are auto-spawned if they don't exist yet, and their configuration is automatically picked based on the task name (it is either `default` if there is no section matching the task name or `default`, `task_name` if there is).

Support for orogen's master/slave deployments

---

lib/syskit/component.rb
lib/syskit/network_generation/logger.rb
lib/syskit/runtime/connection_management.rb

This is meant to reduce the ability for deadlocks, with tasks
like the logger that is synchronized with virtually everything.

runtime: allow tasks to specify that they can be started even if their inputs are not connected

---

lib/syskit/models/deployment.rb
lib/syskit/network_generation/engine.rb
test/network_generation/test_engine.rb

When mapping the deployed network to currently running tasks, it was a mistake in which tasks were added to the selected_deployments

Fix bug from disconnecting logger

---

lib/syskit/gui/ide.rb
lib/syskit/scripts/ide.rb

This allows to start `syskit ide` to control a remote system without having a bundle to do so. Moreover, it ensures that we don't have to have the same bundle state locally and remotely.

ide: create a runtime-only mode

---

lib/syskit/test/network_manipulation.rb
test/test/test_network_manipulation.rb

Local ports don't need to be disconnected the way writers are, so skip their registration in within the @__orocos_writers array

test: properly handle local ports from ruby tasks in syskit_write

---

lib/syskit/coordination/port_handling.rb
lib/syskit/instance_requirements.rb
lib/syskit/models/bound_data_service.rb
lib/syskit/models/component.rb
lib/syskit/models/composition.rb
lib/syskit/models/composition_child.rb
lib/syskit/models/data_service.rb
lib/syskit/models/port.rb
test/models/test_bound_data_service.rb
test/models/test_component.rb
test/models/test_composition_child.rb
test/models/test_data_services.rb
test/test_instance_requirements.rb

'bind' and 'resolve' are somewhat being used interchangeably in the codebase. This attemps to clean up the usage of both, with the following semantics.
'bind' "binds" a model and an already existing instance, returing the part of the instance that is representative of the model.
~~~
srv_m = DataService.new_submodel
task_m = TaskContext.new_submodel
task_m.provides srv_m, as: 'srv'
srv_m.bind(task_m) # => task_m.srv_m
~~~
'resolve' will more generally resolve relationships between objects. For instance, CompositionChild#resolve_and_bind_child will 'resolve' the child from a root composition and then bind it to the composition child model.
There is an inconsistency in the behavior of InstanceRequirements#bind, though, which always returns its argument (if it is valid), **not** providing a …

models: clean mixup between #resolve and #bind

---

lib/syskit/roby_app/plugin.rb

Depends on:
This is a new flag set by the --ui argument to `syskit test`
The goal is to allow for 'interactive' UI tests, where the UIs are
displayed and we use the user as the 'evaluator' of the result.
Worst than pure tests, but better than "manual" tests.
The need to have it handled in Syskit is that there are requirements
on when orocos/async can be loaded (namely, it has to be loaded before
Orocos.initialize is called)

app: load orocos/async if Conf.ui is set

---

lib/syskit/network_generation/async.rb
lib/syskit/network_generation/system_network_generator.rb
lib/syskit/runtime/apply_requirement_modifications.rb
lib/syskit/test.rb
lib/syskit/test/network_manipulation.rb
lib/syskit/test/spec.rb
test/network_generation/test_async.rb
test/test/test_spec.rb

Syskit's `run_planners` support for InstanceRequirements was not stubbing the generated network,
which was essentially making it useless. Add support for stubbing, which makes test support for
e.g. action state machines compatible with Syskit-defined actions

test: implement stubbing in the run_planners handler

---

lib/syskit/actions/profile.rb
test/test/test_network_manipulation.rb

The tags were not handled as placeholders, which was breaking
stubbing.

test: fix stubbing of networks with tags

---

lib/syskit/models/data_service.rb
lib/syskit/network_generation/system_network_generator.rb
lib/syskit/robot/communication_bus.rb
lib/syskit/robot/master_device_instance.rb
lib/syskit/test/network_manipulation.rb
test/models/test_data_services.rb
test/network_generation/test_engine.rb
test/robot/test_communication_bus.rb
test/robot/test_master_device_instance.rb

* allow for a com bus to be run on another com bus. This allows for a logical com layer (e.g. NMEA2000) to be built to top of a lower-level one (e.g. CAN)
* allow the out-service on the com bus task to be static. The in-service could already be.
* add tests for the main com bus definition point, `#attach_to`

Add flexibility to combus definitions

---

lib/syskit/orogen_namespace.rb
test/test_orogen_namespace.rb

Once upon a time, a few years ago, Matthias implemented namespace
support in orogen. The main goal was to allow to define components
in a 'test' namespace, which would be disabled by default and only
enabled if one wants to run the orogen package's tests.
This gives access to tasks defined with OroGen's namespace
support through the OroGen toplevel namespace, e.g.
`OroGen.iodrivers_base.test.DriverTask` for `iodrivers_base::test::DriverTask`

support nested namespaces in OroGenNamespace

---

lib/syskit/models/task_context.rb
lib/syskit/orogen_namespace.rb
test/models/test_task_context.rb

This allows plugins (e.g. syskit-log) to overload where their
model(s) are registered.

move task context model registration to #register_model

---

lib/syskit/exceptions.rb
lib/syskit/instance_requirements.rb
lib/syskit/models/configured_deployment.rb
lib/syskit/models/deployment_group.rb
lib/syskit/models/task_context.rb
lib/syskit/network_generation/engine.rb
lib/syskit/network_generation/system_network_deployer.rb
lib/syskit/roby_app/configuration.rb
lib/syskit/test/network_manipulation.rb
lib/syskit/test/task_context_test.rb
test/coordination/test_fault_response_table_extension.rb
test/coordination/test_models_task_extension.rb
test/models/test_deployment_group.rb
test/network_generation/test_engine.rb
test/network_generation/test_system_network_deployer.rb
test/test/test_network_manipulation.rb
test/test_task_context.rb

Depends on:
Note: the orogen dependency is needed for the change in the syskit_stub method.
The method now resolves models using the process server's own loader instead
of the hardcoded global Roby.app, which triggered a limitation in orogen's loaders
design.
Deployment groups were introduced to refactor the way deployments
were declared and managed.
Pre-groups, all deployments were declared at the level of the global
configuration, and chosen using `prefer_deployed_tasks`. This showed
serious limitations (apart from the ugliness of the globality of it
...). The two main usability issues were:
1. deployments are defined in the robot config and used in profiles. The
link between the two is implicit. Reusing a deployed profile turned
out to be difficult, as was "instanciating" a profile …

Change how deployments are selected

---

lib/syskit/network_generation/dataflow_dynamics.rb
test/network_generation/test_dataflow_dynamics.rb

Bursts were bizarrely handled, fed as a trigger of size 1 and period
"dev.period * dev.burst".  I can't find any justification for this in
the history, so reset it to a period of zero (meaning "count one
burst").
The code iterates on ports from the device service, and was adding the
port name as declared in the service to handled_ports.  This meant that
the wrong port name was passed to done_port_info later in the method and
could lead to a failure in the end.
Last, but not least, the code was iterating on inputs, not outputs which
makes no sense given that a device periods characterizes the data it
produces.

fix multiple bugs in flow dynamics computation related to busses

---

lib/syskit/data_flow.rb
lib/syskit/exceptions.rb
lib/syskit/graphviz.rb
lib/syskit/gui/component_network_base_view.rb
lib/syskit/gui/component_network_view.rb
lib/syskit/gui/model_views/profile.rb
lib/syskit/models/port.rb
lib/syskit/network_generation/dataflow_dynamics.rb
lib/syskit/network_generation/engine.rb
lib/syskit/runtime/connection_management.rb
lib/syskit/task_context.rb
test/network_generation/test_dataflow_dynamics.rb
test/network_generation/test_engine.rb
test/runtime/test_connection_management.rb

Since f1672d0 (merged 2019/01), Syskit would not apply *any* of the connection
policies computed during net gen to the runtime plan. Meaning, all
connections except logging would be using data.
Yep.
I found this out while trying to debug a CAN-based driver that
had to deal with bursts of 10 packets, but only seeing 1/3 of them
coming in, regardless of the computed buffer size.
The bug was created by having one line of the commit commented out
(because it wasn't implemented :() and no integration tests related
to this particular issue. This commit fixes both.
The general idea of the change was a good one, though. The problem
it tried to solve was that policy computation would change **one**
element in DataFlow, which would lose information (what are the
requirements exactly ?) and makes it …

fix application of computed policies

---

bin/syskit

Depends on:
Syskit/Roby has its own dependency-loading mechanism, and
in my experience relying on the rock-bundle system to
load dependencies have been very fragile.
Let people use `Roby.app.register_app` to explicitly load
dependencies if they wish to.

do not load rock/bundles if SYSKIT_USE_ROCK_BUNDLES is set to zero

---

lib/syskit/models/deployment.rb
lib/syskit/models/task_context.rb
lib/syskit/orogen_namespace.rb
lib/syskit/roby_app/plugin.rb
test/test_orogen_namespace.rb

So far, deployment models were registered as constants under the Deployments namespace. This was matching what was happening for tasks (under OroGen) and types (under Types).
A few years ago, I changed the Types access to a method-based access, which is much more flexible and does not require changing the case (registering constants require CamelCasing all names) - Types::Base::Samples::RigidBodyState became Types.base.samples.RigidBodyState. I "recently" [probably a year or two ago] did the same move for components (`OroGen.project_name.TaskModel`).
This PR implements the same for deployments, under `OroGen::Deployments`. This allows to use the model name instead of a string in `use_deployment`, and internally avoids altogether the guessing game of "is this string a task model or a …

provide a method-based access to deployment models

---

lib/syskit/port.rb
test/gui/test_runtime_state.rb
test/test_port.rb

The accessors will now be automatically disconnected once the target
port's component gets finalized, or if the actual port component is (in
case of port exports). So far, port readers had an automatic lifetime
only when created in task scripts, and even there it could lead to
weird issues - like having a connected port but no component actually
listening to it (since the target component was stopped).
In addition, since the ports were outliving their target components,
calling `#disconnect` would fail as `#disconnect` was using the
execution engine of the port's component as resolved at disconnection
time. We now cache this value as it can't change in any case.

auto-disconnect port accessors on component finalization 

---

lib/syskit/cli/gen/bus/class.rb.erb
lib/syskit/cli/gen/bus/test.rb.erb
lib/syskit/cli/gen/cmp/class.rb.erb
lib/syskit/cli/gen/cmp/test.rb.erb
lib/syskit/cli/gen/dev/class.rb.erb
lib/syskit/cli/gen/dev/test.rb.erb
lib/syskit/cli/gen/profile/class.rb.erb
lib/syskit/cli/gen/profile/test.rb.erb
lib/syskit/cli/gen/ruby_task/class.rb.erb
lib/syskit/cli/gen/ruby_task/test.rb.erb
lib/syskit/cli/gen/srv/class.rb.erb
test/cli/test_gen_main.rb

Depends on:
Make sure they pass rubocop, and use new constructs (e.g.
Syskit.extend_task) instead of old ones

cli: modernize the gen templates

---

.simplecov
lib/syskit/test/execution_expectations.rb
test/test/test_execution_expectations.rb

Depends on:
- create the `.matching` refinement to the predicates, allowing to filter
the samples against a predicate, for instance because one is looking
for an (asynchronous) state change
- create `have_new_samples` to find more than one sample

 expand on the `have_.*_sample` riff

---

test/network_generation/test_engine.rb

The create_deployment_model helper would create the tasks and the
deployments. It turns out that (unexpectedly), Syskit deployment
models would not hold a reference to the corresponding Syskit
task models (it only refers to the orogen objects), and sometimes
the syskit models would be garbage collected before they're needed.
I never saw this in the wild, but I think it is something that
should ultimately be fixed at the deployment level.

test: fix flaky test

---

.rubocop_todo.yml
.simplecov
lib/syskit/test/network_manipulation.rb
lib/syskit/test/profile_assertions.rb
lib/syskit/test/spec.rb
lib/syskit/test/stub_network.rb
lib/syskit/test/stubs.rb
lib/syskit/test/task_context_test.rb
test/test/test_network_manipulation.rb
test/test/test_stub_network.rb
test/test/test_stubs.rb
test/test_task_context.rb

The predicates will now plan the actions that are non-syskit
(using Roby's own mechanism run_planners) and finally run
the predicate on what's left.

 handle plain actions in the syskit-specific predicates

---

lib/syskit/gui/runtime_state.rb

Depends on:
With this, whenever the IDE is started with
syskit ide --host=localhost:5002
Clicking 'start' within the IDE will start the controller with the
--host=5002 option.

ide: start the syskit app with the --port argument matching the ide's --host argument

---

lib/syskit/network_generation/merge_solver.rb
test/network_generation/test_merge_solver.rb

If the merge solver ends up looking at two subnets that share a given task instance, it may (will ?) decide to merge the task onto itself, which triggers a sanity check.
The error was within the "needs merge" determination function, which was not checking for "strictly identical" cases.

net_gen: fix merging of networks that have shared task instances

---

lib/syskit/test/instance_requirement_planning_handler.rb
lib/syskit/test/network_manipulation.rb
lib/syskit/test/self.rb
lib/syskit/test/spec.rb
test/test/test_network_manipulation.rb
test/test/test_spec.rb

Depends on:
It runs the deployer on the complete plan. It uses run_planners,
and is therefore able to run method or state machine actions
before it checks for the deployment state.
It returns a mapping from the missions as they currently are to
the deployed missions

define deploy_current_plan

---

lib/syskit/test/instance_requirement_planning_handler.rb
lib/syskit/test/stub_network.rb
test/test/test_stub_network.rb

The components' replacement would not be propagated, which leads to
the plan services not tracking them properly.
Plan services are in particular used by the Syskit `run_planners` handler to track what is being deployed.
This fixes `deploy_current_plan` when some missions become children of others during deployment.

test: fix components not being properly tracked by plan services during stubbing

---

lib/syskit/deployment.rb
lib/syskit/remote_state_getter.rb
test/test_remote_state_getter.rb

A.k.a. almost never. This getter is here to workaround the lack
of a state port, which never happens on Rock anymore. It was spawning
one thread and polling the '#rtt_state' remote call for basically
nothing

start the threaded state getter only when needed

---

lib/syskit/deployment.rb
lib/syskit/roby_app/unmanaged_process.rb
test/test_deployment.rb

Depends on:
The current implementation of Deployment's stop command was a
hornet's nest. Really. No kidding. It would basically have a 50-50
chance to do something wrong if called outside the normal flow (i.e.
outside of Roby's garbage collection mechanism)
1. STOPPED/RUNNING race condition
The cleanup loop was testing for rtt_state to check if the task
is STOPPED before attempting to clean it up. If, at the same time,
Syskit is itself trying to configure or start it, this races.
It would sometime abort the deployment's stop.
2. Blocking behavior because of task cleanup
The current flow would cleanup the tasks *and* let the orocos.rb's
implementation of Process also clean them up. It's OK-ish in normal
circumstances, but is rather obviously sub-optimal in basically
every non-nominal …

rework Deployment's stop handling

---

lib/syskit/network_generation/async.rb
test/network_generation/test_async.rb

Some of these options (namely, compute_deployments) control whether
apply has to finalize things that were prepared in the async phase.
When set incorrectly, they can lead to failures in the deployment
phase.
Note that this does not impact the normal flow (as it uses only
default options, which are coherent). It led to failures during
tests.

net_gen: carry options passed to Async.start/.prepare to the apply step

---

lib/syskit/network_generation/system_network_generator.rb
test/network_generation/test_system_network_generator.rb

"meaningful arguments" are the arguments that are actually declared
in the task model (with the `argument`) property. These arguments
are constrain what can e.g. replace the task, or if the task may
or may not start (when they are unset).
However, it is possible to pass other arguments, which are useful
to the task, but e.g. should not constrain the replacements
However, during instanciation, syskit would set {#fullfilled_model}
explicitely with all arguments given to the InstanceRequirement object
Since an explicit #fullfilled_model takes precedence, these not-meaningful
arguments were affecting replacement checks.

net_gen: when instanciating, set fullfilled_model only with meaningful arguments

---

.rubocop_todo.yml
lib/syskit/test/profile_assertions.rb
test/test/test_profile_assertions.rb

ProfileAssertion iterates on the first argument to the assertion, i.e.
tests them in isolation. There was so far no way to test "check that
this or these actions can be deployed/instanciated along with this/these
other actions and compositions.
This can be used e.g. to test that "permanent services" that always
run do not interfere with the deployment of definitions from other
profiles.

test: implement together_with argument for assert_can_instanciate and _deploy

---

lib/syskit/placeholder.rb
test/test_placeholder.rb

While replacing "real" tasks do not involve port mappings (the
names are stable in the model hierarchy), replacing a placeholder
task involved port mapping the services to the actual names. This
commit implements that.

fix replacement of a placeholder task

---

lib/syskit/network_generation/async.rb
lib/syskit/network_generation/engine.rb
lib/syskit/network_generation/system_network_generator.rb
lib/syskit/runtime/apply_requirement_modifications.rb
test/network_generation/test_async.rb
test/runtime/test_apply_requirement_modifications.rb

The current implementation had a race condition in case the
generation was already in progress. It was queueing the transaction
discard using a execution_engine.once block, but that was not
guaranteed to be executed before the next apply_require_modification
call. When apply_require_modification was called first, it would
apply the changes.
Moreover, the applied transaction would have been generated while
(1) the syskit_current_resolution_keepalive transaction had been
discarded, and (2) while another resolution could have been in
progress.
A.k.a. recipe for disaster.
Simplify the execution flow by only "cancelling" in #cancel, letting
the generation finish (or, in case the future was pending, being
cancelled - which is also transitioning to finished), and handle
the cancellation in …

fix cancellation of asynchronous plan generation

---

lib/syskit/roby_app/remote_processes/server.rb
test/roby_app/remote_processes/test_remote_processes.rb

Randomly - but rather often - CI would fail with "426 Connection closed; transfer aborted."
I could pinpoint the problem with the Net::FTP library closing the connection after the transfer is finished, but the remote side (ftpd) ending up getting a CONNRESET instead of a plain EOF. This would happen on SSL, I'm guessing because the SSL shutdown probably does a back-and-forth between client and server.
While I could reliably reproduce the bug on our CI's containers (Ubuntu 18.04, Ruby 2.5.1p57), I could not get it to trigger on my dev machine (Ubuntu 20.04, Ruby 2.7.0p0 and 2.7.1p83 compiled with rbenv). Even 2.5.0p0 and 2.5.1 do not trigger here.
So, there's something fishy here. I'm disabling TLS for the data connection for now, as it is unusable as it is. It's only half-bad as the ports …

Fix random bug related to ssl in ci

---

lib/syskit/network_generation/merge_solver.rb
test/network_generation/test_engine.rb

The composition merge step would use dependency_graph.each_vertex,
but tasks that never had dependency relationships are not included
in the graph.
Simply iterate over plan.each_task instead.

net_gen: fix plan merge for compositions without children

---

lib/syskit/dynamic_port_binding.rb
test/test_dynamic_port_binding.rb

The symptom would be an error looking like
~~~
${TASK} has no child with the role '${CHILD_NAME}', actually, it has no child at all
~~~

in dynamic port binding updates, ignore composition ports that can't be resolved

---

lib/syskit/deployment.rb
lib/syskit/models/task_context.rb
lib/syskit/roby_app/plugin.rb
lib/syskit/task_context.rb
test/models/test_task_context.rb
test/test_deployment.rb
test/test_task_context.rb

On top of https://github.com/rock-core/tools-syskit/pull/289
The title sums it up ... it's embarrassing.
The reconfiguration logic was completely broken. Essentially, Syskit would always reconfigure, except if a component is configured with its default parameters. And also if it has no dynamic services.
The bad part is that fixing this required user-facing changes. This pull request require components to define a `update_properties` method in which the property updates are made. This method must be idempotent, and will be called in all cases. `configure` is called after the `cleanup` for non-idempotent configuration, as e.g. calling operations (the `canbus` component needs that for instance).
This change is forward and backward compatible though. Current orogen classes that do not define …

Fix reconfiguration logic

---

lib/syskit/test/execution_expectations.rb
test/test/test_execution_expectations.rb

They return 'false' which was interpreted by the implementation as
"no new sample"

test: fix have_no_new_sample/have_new_samples for boolean ports

---

Rakefile
lib/syskit/cli/gen/syskit_app/config/init.rb
lib/syskit/component.rb
lib/syskit/deployment.rb
lib/syskit/exceptions.rb
lib/syskit/instance_requirements.rb
lib/syskit/models/task_context.rb
lib/syskit/network_generation/engine.rb
lib/syskit/remote_state_getter.rb
lib/syskit/roby_app/configuration.rb
lib/syskit/roby_app/remote_processes/server.rb
lib/syskit/runtime/update_task_states.rb
lib/syskit/task_context.rb
test/live/run
test/live/test_blocking_hooks.rb
test/live/test_fatal_error.rb
test/live/test_state_reader_disconnection.rb
test/models/test_task_context.rb
test/runtime/test_connection_management.rb
test/runtime/test_update_task_states.rb
test/test_component.rb
test/test_deployment.rb
test/test_task_context.rb

Depends on:
This is built on top of #293 
This pull request is an attempt to (finally) deal with some rather dark corners of component execution. The issue at hand is how to handle components that do not exactly follow the implicit contract of "please do not block" and "report your state". Up until now, they would not really be dealt with, and the system could simply start to do Bad Things.
This type of failure in pre-start states (which are not visible to Syskit) are handled through a new internal flag in Deployment that marks the component as "in fatal". After being started, they are put in quarantine, the support of which has been reworked in https://github.com/rock-core/tools-roby/pull/198 for this purpose.
In both cases, the system will not allow any usage of these components in the …

Handle dark corners of component execution

---

lib/syskit/cli/gen/syskit_app/config/init.rb

While new apps do not need to be backward compatible, we auto-generate
apps for orogen tests, which have to be. Mention the two configuration
variables, but set them to true for now

fix(app): re-enable export_types and syskit_model_constant_registration for backward compatibility

---

cmake/Syskit.cmake

Instead of clearing it to make sure logs end up in bundle/, set
it to ROCK_TEST_LOG_DIR so that they are part of the test result
logs, which are saved by Autoproj
This allows to inspect networks and component test logs after a failure,
which is quite obviously useful

feat(orogen-test): set ROBY_BASE_LOG_DIR to ROCK_TEST_LOG_DIR

---

test/live/run
test/live/test_blocking_hooks.rb
test/live/test_fatal_error.rb

Depends on:
These `live` tests have been introduced recently to allow running a full Syskit event loop during the tests, by executing
the files one by one under `syskit orogen-test`
Turns out that the `run` script did not call sh with -e, and that - therefore - any error was ignored. To add insult to injury,
the script itself had a bug (orogen-test has no --logs argument) and the tests were not passing.
Oh well.
Anyways, fix the run script and fix the test. Luckily, I did not manage to find bugs in the code-under-test (but did
find one in Roby's test harness)

fix: live tests

---

lib/syskit/runtime/update_task_states.rb
lib/syskit/task_context.rb
test/live/test_state_reader_disconnection.rb

The bug was a conjunction of three things:
- The tests related to losing both the state reader and the state getter
would have `join_all_waiting_work(true)`. This caused the tests
to wait for the blocked method (usually stop) to return.
- update_task_states would call TaskContext#validate_state_reader_connected,
but still read new states.
- The tests would only mock the remote state getter connected? method,
which caused update_task_states
So, essentially, we had a race condition between the expect_execution
leaving (that is, the blocking method returning) and the deployment_kill
call. In essence, the tests were not testing what we wanted, that is that
the runtime code would stop reading and reacting to state.
The test got changed to join_all_waiting_work(false) until quarantine,
then …

fix(test): spurious test failure in live test

---

lib/syskit/composition.rb
test/test_composition.rb

Composition#executable? is implemented so that compositions are started
only when all their children are started.
However, if we want to use a child to actually implement an asynchronous
start, this fails: the child emits success, becomes non-executable which
blocks the emission of start.
Modify Composition#executable? to ignore non-pending children, which
are either executable (if running) or will never be (if finished)

fix(runtime): ignore finished children in Composition#executable?

---

lib/syskit/droby/enable.rb
lib/syskit/droby/v5/droby_dump.rb
lib/syskit/models/base.rb
lib/syskit/models/data_service.rb
lib/syskit/models/task_context.rb
lib/syskit/network_generation/engine.rb
lib/syskit/roby_app/plugin.rb
lib/syskit/scripts/ide.rb
lib/syskit/task_context.rb
test/droby/test_droby_dump.rb
test/models/test_deployment.rb
test/models/test_task_context.rb
test/roby_app/test_rest_api.rb
test/roby_app/test_rest_deployment_manager.rb
test/test_deployment.rb

Depends on:
On top of https://github.com/rock-core/tools-syskit/pull/307 (style fixes)
The current droby loading implementation was always trying to merge remote models with local ones (in Roby.app). This was coming from the (long lost) legacy of distributed roby, where local and remote systems wanted to make sure they were agreeing on the models that they were manipulating.
However, in the only existing use case of the droby implementation - logs - this is very harmful.
- it fails if local models differ from remote ones (i.e. if a local orogen project got changed since a log file was generated)
- it triggers load-time hooks that make us load orogen extension files, which is actually rather slow
This pull request reimplements that part of the loading logic to isolate the loaded models …

fix(droby): isolate loaded droby models

---

lib/syskit/droby/enable.rb
lib/syskit/droby/v5/droby_dump.rb
lib/syskit/models/task_context.rb

[20ce287](https://github.com/rock-core/tools-syskit/commit/20ce287864098a0c6390fb54a934b7d98aa8f476) changed the log file format, while keeping backward compatibility on the reading side.
Unfortunately, that means that older log files could still not be loaded if they had incompatible types. This commit adds a way to disable loading orogen models completely, which provides the same functionality, albeit losing some information on the way.

fix: successfully load log files created before 20ce287 that have incompatible types

---

lib/syskit/models/ruby_task_context.rb

All the other deployments are there. `Deployment` was clearly a typo

fix: register ruby tasks deployments on `Deployments`

---

lib/syskit/roby_app/configuration.rb

The current code was trying to connect to a process server
on localhost, but at the process server's configured port. This
really made no sense.
--single is meant to provide us with a way to run a distributed
system on a single machine. What makes the most sense w.r.t.
process servers is to simply use the local one in this case.

fix: use the localhost process server in --single mode

---

lib/syskit/graphviz.rb
lib/syskit/gui/component_network_base_view.rb
lib/syskit/network_generation/dataflow_dynamics.rb
lib/syskit/network_generation/engine.rb
lib/syskit/task_context.rb

A not-so-well-known feature of Syskit is the ability to calculate and propagate a port's expected dynamics (period and bursts), and use this to calculate connection policies - especially buffer sizes.
The functionality is still working, but displaying the result was broken - probably for a very long time. This pull request restores the display, while at the same time storing the trigger information on the task themselves for easier access / analysis.
The last commit disables validations if a deployed network has errors. This is necessary for e.g. our system which resolves some of the services at runtime.

fix(gui): display triggers and logging policies in the IDE

---

lib/syskit/instance_requirements.rb
lib/syskit/test/profile_assertions.rb
test/test_instance_requirements.rb

InstanceRequirements is the go-to object to represent ready-to-instanciate models (with e.g. arguments). This fixes a use-case, where one would need to inject a specific bound service, while also setting arguments.

feat: allow passing a service expressed as an InstanceRequirements in IR#select_service

---

lib/syskit/scripts/ide.rb

The development mode turns on features that are specific to a running
Syskit instance, and are useless (and even could be harmful) in the IDE.
I discovered this because after I disabled the rebuilding of orogen
models, the IDE started reporting exceptions related to configuration
loading. At runtime, it was discovering configuration changes and tried
to reload the models using the (now empty) rebuilt models from remote.
Which obviously fails because they had no properties.

fix(cli): disable development mode in `syskit ide`

---

lib/syskit/exceptions.rb
lib/syskit/task_context.rb
test/models/test_task_context.rb
test/test_task_context.rb

read-only tasks are tasks that share a resource (i.e "#orocos_task") with another task running on a different Syskit instance.
In that way, it does not interfere with the resource, as it will only perform read operations, skip setup, and also not stop when interrupted (so child tasks are not garbage collected).

feat: add 'read_only' attribute for TaskContext

---

lib/syskit/actions/action_model.rb
lib/syskit/instance_requirements.rb
test/actions/test_action_model.rb
test/test_instance_requirements.rb

This is generally harmless ... unless two actions end up being
handled by the same task.
The regression here for me was the impossibility to spawn two gazebo
links from the same ModelTask. Network generation would create the
same task, but with different job IDs, which then cannot be merged.

fix: do not set job_id on the plan patterns' placeholder tasks

---

lib/syskit/scripts/ide.rb

Essentially, we must call require_app_dir before we process the robot()
setup, which in this case is done by Scripts.common_options,
or the list of robots won't be the right one.
The fix is to hand-detect --runtime-only and act accordingly

fix(app): fix syskit ide -rROBOT when ROBOT is defined within config/app.yml

---

lib/syskit/roby_app/remote_processes.rb
lib/syskit/roby_app/remote_processes/client.rb
lib/syskit/roby_app/remote_processes/protocol.rb
lib/syskit/roby_app/remote_processes/server.rb
test/roby_app/remote_processes/test_remote_processes.rb

This should allow to recover from Syskit crashes (provided that a
watchdog kills the Syskit process). It does not apply to local process
servers, as they are always started fresh. But local process servers
(and locally started components) can be terminated by e.g. systemd
along with syskit itself. This is meant to deal with the remote ones.

feat: optionally kill all running deployments of a process server on connection

---

lib/syskit/models/deployment_group.rb
lib/syskit/roby_app/plugin.rb
test/roby_app/test_plugin.rb

It needed a `each_configured_deployment` method from `Syskit.conf` which doesnt exist anymore.

fix: update syskit start all deployments method 

---

lib/syskit/roby_app/configuration.rb

This should allow to recover from Syskit crashes (provided that a watchdog kills the Syskit process). It does not apply to local process servers, as they are always started fresh. But local process servers (and locally started components) can be terminated by e.g. systemd along with syskit itself. This is meant to deal with the remote ones.

feat(app): optionally call kill_all on newly connected process servers

---

lib/syskit/deployment.rb
lib/syskit/roby_app/remote_processes/client.rb
lib/syskit/roby_app/remote_processes/process.rb
lib/syskit/roby_app/remote_processes/protocol.rb
lib/syskit/roby_app/remote_processes/server.rb
lib/syskit/roby_app/unmanaged_process.rb
lib/syskit/roby_app/unmanaged_tasks_manager.rb
lib/syskit/runtime/update_deployment_states.rb
test/roby_app/remote_processes/test_remote_processes.rb
test/roby_app/test_configuration.rb
test/roby_app/test_unmanaged_tasks.rb
test/runtime/test_update_deployment_state.rb
test/test_deployment.rb
test/test_task_context.rb

Depends on:
We are changing orocos to get the task's IOR through a pipe with orogen instead of the name service to discover the task.

feat: use the IORs as published by the orogen deployments to resolve task contexts
