generators/bus/USAGE
generators/bus/bus_generator.rb
generators/bus/templates/class.rb
generators/bus/templates/require_file.rb
generators/bus/templates/test.rb
generators/cmp/USAGE
generators/cmp/cmp_generator.rb
generators/dev/USAGE
generators/dev/dev_generator.rb
generators/dev/templates/class.rb
generators/dev/templates/require_file.rb
generators/dev/templates/test.rb
generators/orogen/USAGE
generators/orogen/templates/class.rb
generators/profile/USAGE
generators/profile/templates/class.rb
generators/srv/USAGE
generators/srv/templates/test.rb
lib/syskit/models/task_context.rb
lib/syskit/network_generation/logger.rb
lib/syskit/roby_app/configuration.rb
lib/syskit/roby_app/plugin.rb
test/models/test_task_context.rb
test/roby_app/test_plugin.rb

This depends on the relevant PRs to be merged on Roby (rock-core/tools-roby#16 and rock-core/tools-roby#17)

Syskit new naming scheme

---

lib/syskit/actions/profile.rb
lib/syskit/roby_app/plugin.rb
lib/syskit/test.rb
lib/syskit/test/base.rb
lib/syskit/test/component_test.rb
lib/syskit/test/self.rb
lib/syskit/test/spec.rb
test/data/plugin_remote_model_loading.orogen
test/models/test_port.rb
test/test_task_context.rb

This depends on rock-core/tools-roby#16

Small test fixes

---

generators/orogen/orogen_generator.rb
generators/orogenconf/USAGE
generators/orogenconf/orogenconf_generator.rb
generators/orogenconf/templates/conf.yml

It is the equivalent to 'orococonf extract', only allowing us to have
a single consistent CLI interface.

gen: add the orogenconf generator

---

bin/syskit
lib/syskit/graphviz.rb
lib/syskit/gui/expanded_job_status.rb
lib/syskit/gui/ide.rb
lib/syskit/gui/job_state_label.rb
lib/syskit/gui/job_status_display.rb
lib/syskit/gui/model_browser.rb
lib/syskit/gui/model_views/profile.rb
lib/syskit/gui/runtime_state.rb
lib/syskit/gui/state_label.rb
lib/syskit/gui/widget_list.rb
lib/syskit/scripts/ide.rb
lib/syskit/shell.rb
lib/syskit/task_context.rb

This is a reopen of #75 after a instantly-reverted wrong push to master

Create the runtime panel in the IDE

---

bin/syskit
lib/syskit/component.rb
lib/syskit/deployment.rb
lib/syskit/gui/component_network_base_view.rb
lib/syskit/gui/component_network_view.rb
lib/syskit/gui/ide.rb
lib/syskit/gui/instanciate.rb
lib/syskit/gui/model_views/component.rb
lib/syskit/gui/model_views/composition.rb
lib/syskit/gui/model_views/profile.rb
lib/syskit/gui/page.rb
lib/syskit/gui/testing.rb
lib/syskit/instance_requirements.rb
lib/syskit/models/component.rb
lib/syskit/network_generation/engine.rb
lib/syskit/roby_app/configuration.rb
lib/syskit/roby_app/plugin.rb
lib/syskit/scripts/ide.rb
lib/syskit/scripts/process_server.rb
lib/syskit/task_context.rb
lib/syskit/test/network_manipulation.rb
lib/syskit/test/self.rb
test/actions/test_profile.rb
test/models/test_component.rb
test/network_generation/test_engine.rb
test/network_generation/test_merge_solver.rb
test/robot/test_robot_definition.rb
test/test_component.rb
test/test_task_context.rb

Depends on https://github.com/rock-core/tools-roby/pull/34

Improvements

---

lib/syskit/exceptions.rb
lib/syskit/network_generation/engine.rb
lib/syskit/network_generation/system_network_generator.rb
test/network_generation/test_system_network_generator.rb

net_gen: fix SystemNetworkGenerator NOT running the validation hooks

---

lib/syskit/roby_app/configuration.rb

This should allow to use multiple name services.

roby_app: allow to use_unmanaged_task on a specific task manager

---

lib/syskit/gui/ide.rb
lib/syskit/scripts/ide.rb

Depends on https://github.com/rock-core/tools-roby/pull/56

ide: fix passing the port to "syskit ide"

---

lib/syskit/gui/testing.rb
lib/syskit/roby_app/plugin.rb
lib/syskit/scripts/ide.rb
lib/syskit/test/network_manipulation.rb

Update related to https://github.com/rock-core/tools-roby/pull/57

Fix test file discovery

---

lib/syskit/gui/logging_configuration.rb
lib/syskit/gui/logging_configuration_item.rb
lib/syskit/gui/logging_configuration_item_base.rb
lib/syskit/gui/logging_groups_item.rb
lib/syskit/gui/ruby_item.rb
lib/syskit/gui/runtime_state.rb
lib/syskit/shell_interface.rb
test/test_gui_logging_configuration.rb
test/test_gui_runtime_state.rb
test/test_shell_interface.rb

So, I will do all the work here. Feel free to comment whenever you like.  I'm not sure what branch I should be basing this on (there are no shell interface tests at all on master :()

ide: add a gui to manage logging configuration

---

lib/syskit/gui/batch_manager.rb

When e.g. the connection fails

ide: do not crash if batch.__process fails

---

lib/syskit/gui/html_page.rb
lib/syskit/gui/instanciate.rb
lib/syskit/gui/page_extension.rb

`syskit instanciate` sub command was broken due to wrong subclassing... @doudou double check this please

ide: fix page subclass inheritance

---

lib/syskit/graphviz.rb
lib/syskit/gui/page_extension.rb
lib/syskit/models/bound_data_service.rb
lib/syskit/models/bound_dynamic_data_service.rb
lib/syskit/models/component.rb
lib/syskit/models/dynamic_data_service.rb
lib/syskit/network_generation/engine.rb
test/models/test_bound_data_service.rb
test/models/test_bound_dynamic_data_service.rb
test/models/test_component.rb
test/models/test_dynamic_data_service.rb
test/network_generation/test_engine.rb

fix corner cases in modelling and network generation

---

lib/syskit/task_configuration_manager.rb
test/cli/test_gen_main.rb

pass config/orogen/.cache as cache_dir to speedup loading configuration

---

lib/syskit/gui/runtime_state.rb

ide: fix crashes when Syskit quits during some calls

---

lib/syskit/droby/v5/droby_dump.rb

This is yet-another bug caused by things being marshalled and
unmarshalled in a different order. I'm fed up with this, will
implement the proper (backward-compatible !) solution soon.

droby: fix yet-another unmarshalling ordering bug

---

lib/syskit/port.rb
test/test_port.rb

expose some APIs from orocos.rb to Syskit's Port/Reader/Writer API

---

lib/syskit/gui/ide.rb
lib/syskit/gui/job_status_display.rb
lib/syskit/gui/runtime_state.rb
lib/syskit/gui/widget_list.rb

Improvements form @jcmonteiro. Thanks Joao !

improvements to the IDE runtime workflow

---

lib/syskit/component.rb
lib/syskit/composition.rb
lib/syskit/instance_requirements.rb
lib/syskit/models/composition.rb
test/models/test_composition.rb

This seemed to be broken ever since the introduction of instanciation
templates at least 2 years ago .... Probably not a very used
functionality

fix handling of composition configurations

---

cmake/Syskit.cmake
cmake/syskit-config.cmake
lib/syskit/cli/main.rb
lib/syskit/test/network_manipulation.rb
lib/syskit/test/roby_app_helpers.rb
lib/syskit/test/task_context_test.rb
test/test/fixtures/task_context_test/abstract_live.rb
test/test/fixtures/task_context_test/abstract_simulation.rb
test/test/test_network_manipulation.rb
test/test/test_task_context_test.rb

add support for testing oroGen components using Syskit

---

lib/syskit/test/network_manipulation.rb
test/test/test_network_manipulation.rb

And disconnect them on teardown.
syskit_create_writer is necessary (as opposed to using syskit_write)
if the component behaves differently if (1) there is no connection
(e.g. iodrivers_base during configuration) or (2) if there is NoData.
syskit_create_reader allows to mock a component that would "reply"
to the task under test within a poll block, instead of having to
play with have_one_new_sample in execution expectation blocks. Not
having to do the latter makes sure that we can concentrate on the test
itself.
The "introduction" use case is the ability to unit test a component
built on top of iodrivers_base. For this component we need to interact
with the io_raw_in and io_raw_out ports to fake the actual device to
be allowed to configure and start the component.

test: add helpers to create reader and writers during tests

---

lib/syskit/roby_app/configuration.rb
test/roby_app/test_configuration.rb

This allows each remote system to be self-sufficient, instead of
relying on a root name service to be available.

app: allow configuring the name service used to resolve process server tasks

---

lib/syskit/gui/testing.rb
test/gui/test_testing.rb

It seems that minitest changed the attribute name from 'exception'
to 'error' :(

 test: fix error reporting 

---

test/runtime/test_connection_management.rb

The test was mis-using what turned out to be a bug in
ExecutionEngine#garbage_collect, which failed when that bug got fixed.
"Simulate" the actual reconfiguration process to get a proper behavior

test: rewrite a reconfiguration-related test to properly mock an actual reconfiguration

---

.rubocop_todo.yml
lib/syskit/actions/profile.rb
lib/syskit/models/deployment_group.rb
lib/syskit/roby_app/configuration.rb
test/actions/test_profile.rb
test/models/test_deployment_group.rb
test/test_deployment.rb

It was untested and full of bugs

fix the profile-level deployment group interface

---

manifest.xml

depend on an orogen package to hold orogen-generated packages for tests

---

lib/syskit/composition.rb
test/test_composition.rb

Missing children during plan modifications such as replacements may
happen, as for instance replacing a running composition by an abstract
one, or a half-broken composition (with some children missing) with
a working one.

ignore missing children when triggering connection updates

---

lib/syskit/remote_state_getter.rb
lib/syskit/task_context.rb
test/live/run
test/live/test_blocking_hooks.rb
test/live/test_kill_while_stopping.rb
test/test_remote_state_getter.rb

fix(runtime): fix deadlock in RemoteStateGetter

---

lib/syskit/test/profile_assertions.rb
test/test/test_profile_assertions.rb

Profile assertions (assert_can_deploy, assert_can_instanciate, ...)
can already handle a few cases of derived actions based on Syskit
actions (i.e. action state machines). This commit significantly
expands it by handling method actions (which then get called)
and resolving models from there.

fix(test): handle more cases in the profile assertions tests

---

lib/syskit/deployment.rb
lib/syskit/models/configured_deployment.rb
lib/syskit/models/deployment_group.rb
lib/syskit/network_generation/engine.rb
lib/syskit/test/network_manipulation.rb
lib/syskit/test/stub_network.rb
lib/syskit/test/stubs.rb
test/models/test_configured_deployment.rb
test/models/test_deployment_group.rb
test/network_generation/test_logger.rb
test/test_deployment.rb
test/test_task_context.rb

Depends on:
On top of https://github.com/rock-core/tools-syskit/pull/321

feat: add read_only attribute to configured deployment

---

lib/syskit.rb
lib/syskit/deployment.rb
lib/syskit/logger_service.rb
lib/syskit/network_generation/logger.rb
lib/syskit/roby_app/configuration.rb
lib/syskit/roby_app/plugin.rb
lib/syskit/roby_app/tmp_root_ca.rb
lib/syskit/test/spec.rb
test/live/test_blocking_hooks.rb
test/live/test_state_reader_disconnection.rb
test/network_generation/test_logger.rb
test/roby_app/test_plugin.rb

Depends on:
Syskit implementation for triggering Log Rotation and Transference
Built on top of:

feat: implement rotation of data logs
